### Default Setting
server:
  port: 9999

spring:
  config:
    additional-location: classpath:properties/
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        type: debug
        default_batch_fetch_size: 100
    open-in-view: false
    main:
      allow-bean-definition-overriding: true

# Logging
logging:
  level:
    org.hibernate.SQL: debug

# xe
hanpass:
  db.encrypt.key: hanpass_uway_payment123!
  xe.account:
    id: hanpassco.,ltd.422150019
    api.key: nc0f7m12bf8r3ugkr72gt120iv
  convert.url: https://xecdapi.xe.com/v1/convert_from.json

---
### local ###
spring:
  profiles: local

# datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.7.214:3306/uway-test?autoReconnect=true&charaterEncoding=utf-8
    username: root
    password: Gksvotm12#$
    dbcp2:
      validation-query: select 1
#korea invest
hanpass:
  ht.rate.url: http://192.168.7.39:8080/remittance/exchange-rates
  api.save.ht-rate.url: http://localhost:8888/exchange-rate/ht

---
### develop ###
spring:
  profiles: dev

# datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.7.214:3306/uway?autoReconnect=true&charaterEncoding=utf-8
    username: root
    password: Gksvotm12#$
    dbcp2:
      validation-query: select 1

#korea invest
hanpass:
  ht.rate.url: http://192.168.7.39:8080/remittance/exchange-rates
  api.save.ht-rate.url: http://192.168.77.117:8888/exchange-rate/ht

---
### production ###
server:
  ssl:
    enabled: true
    key-store: /home/tomcat/ssl/hanpass_2019_2021.keystore
    key-store-password: hanpassroot2017!
    key-store-type: jks
    key-alias: tuition-noti.hanpass.com
spring:
  profiles: prd

# datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.23.130.200:3306/uway?autoReconnect=true&charaterEncoding=utf-8
    username: root
    password: hanpasspg2020!@#
    dbcp2:
      validation-query: select 1

#korea invest
hanpass:
  ht.rate.url: http://192.168.7.41:8080/remittance/exchange-rates
  api.save.ht-rate.url: https://tuition-api.hanpass.com/exchange-rate/ht